### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [mysilkyheart/sistem_skripsi#1]
Good day Sir I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before i begin my design. Hoping for your positive feedback. Thanks

**Comment by deanufriana** [comment]
of course sir you can make it but i cant really pay you for your design i make this just for learn and fun it programming, if you really make it, it really help me because i not good in design thanks before sir..

**Comment by mansya** [comment]
sorry for the long response. lately I'm a little busy with work around me. this is the result of my design. How ? do you like it ? if yes please tell me. and if there are changes please tell me.

![sistem skripsi1](https://user-images.githubusercontent.com/33461607/47830699-9d28f800-ddbf-11e8-8742-a50df1fa45fc.png)

![sistem skripsi](https://user-images.githubusercontent.com/33461607/47830627-4c190400-ddbf-11e8-9f18-dbd1cd3da8d5.png)

**Comment by mansya** [comment]
hi sir. how about the continuation of this logo? do you like it ?

**Comment by deanufriana** [comment]
I don't want to interfere with your work either, its ok i will put it in my system. Once again, thank you.

**Comment by mansya** [comment]
you can wait for it. I will do pull requests. and after that I will give all vector files about this logo.

**Comment by deanufriana** [comment]
thanks for your support, bro 😁

**Comment by mansya** [comment]
Hi sir. this is link for acces file vektor this logo project [Drive](https://drive.google.com/open?id=1IwTgmxQDq3NRTPV497oMJD90g8s7Nndr)
